Hotfix autoformatter action
groep-3-there/backend pull request #79
Opened 2023-11-20 14:57 UTC by LukevandePol

added autoformatter

2023-11-20 14:57 UTC, LukevandePol commented
belangerijk dat er geen conflicts zijn

2023-11-21 08:36 UTC, Rikk010 requested changes

2023-11-21 08:36 UTC, Rikk010 commented on src/main/java/matchmaker/backend/controllers/CompanyRequestController.java
> +  @Autowired public CompanyRequestRepository repository;
🤢

2023-11-21 08:37 UTC, florijnm approved these changes

2023-11-21 09:04 UTC, closed without merging